services:
  - type: web
    name: sshx-shell
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: PING_INTERVAL
        value: "120"
